name: townzy
description: "A new Flutter project."
publish_to: 'none' # This prevents publishing to pub.dev

version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  http: ^1.4.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf

    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan-Regular.ttf

    - family: Harmattan_B
      fonts:
        - asset: assets/fonts/Harmattan-Bold.ttf
